import { NextResponse } from 'next/server';
import { createClient } from '@/lib/polymarket/client';
import { z } from 'zod';
import { auth } from '@/lib/auth';
import { logAudit, AuditActions } from '@/lib/audit/logger';

const testCredentialsSchema = z.object({
    apiKey: z.string().min(1),
    apiSecret: z.string().min(1),
    passphrase: z.string().min(1),
});

export const dynamic = 'force-dynamic';

export async function POST(req: Request) {
    try {
        const session = await auth();
        if (!session?.user?.id) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const body = await req.json();
        const validation = testCredentialsSchema.safeParse(body);

        if (!validation.success) {
            return NextResponse.json(
                { error: 'Invalid credentials format' },
                { status: 400 }
            );
        }

        const { apiKey, apiSecret, passphrase } = validation.data;

        // Check for common user error: entering wallet address instead of API Key
        if (apiKey.trim().startsWith('0x')) {
            return NextResponse.json(
                {
                    error: 'Invalid API Key format',
                    details: 'You entered a Wallet Address (starts with 0x). Please enter the API Key (UUID) generated by Polymarket.',
                },
                { status: 400 }
            );
        }

        // Initialize client with provided credentials
        const client = createClient({
            apiKey: apiKey.trim(),
            apiSecret: apiSecret.trim(),
            passphrase: passphrase.trim(),
        });

        try {
            // We use getTrades as a smoke test because /orders returns 405 (Method Not Allowed)
            // getTrades requires valid L2 signature
            await client.clob.getTrades();

            // Log success
            await logAudit({
                userId: session.user.id,
                action: AuditActions.CREDENTIALS_VERIFIED,
                category: 'SETTINGS',
                details: { success: true },
            });

        } catch (apiError: any) {
            console.error('Polymarket API Error during test:', apiError);

            const errorDetails = apiError?.details || { message: apiError?.message };
            const status = apiError?.status || 500;

            // Log failure to database so we can see it in Logs page
            // Using SYSTEM category to ensure it works even if SETTINGS is missing in DB enum
            await logAudit({
                userId: session.user.id,
                action: 'credentials.verification_failed',
                category: 'SYSTEM',
                details: {
                    error: errorDetails,
                    apiKeyPrefix: apiKey.substring(0, 4) + '...',
                    hasSecret: !!apiSecret,
                    hasPassphrase: !!passphrase,
                    status: status
                },
            });

            return NextResponse.json(
                {
                    error: 'Connection failed',
                    details: apiError?.message || 'Invalid API Credentials',
                    debug: {
                        ...errorDetails,
                        status: status
                    }
                },
                { status: 400 }
            );
        }

        return NextResponse.json({ success: true, message: 'Connection successful!' });

    } catch (error) {
        console.error('Test credentials error:', error);
        return NextResponse.json(
            { error: 'Internal server error during test' },
            { status: 500 }
        );
    }
}
